version: "3.8"

services:
  famulex:
    image: registry.coduction.com/famulex:latest
    container_name: Famulex
    build:
      dockerfile: ./Dockerfile
      context: .
    depends_on:
      - famulex_db
    ports:
      - "8080:8080"
    volumes:
      - famulexData:/.data
      - ./backend/src/main/resources/application.properties:/application.properties
      - ./backend/src/main/resources/application-dev.properties:/application-dev.properties
    networks:
      - famulex
    environment:
      SERVER_ADDRESS: 0.0.0.0
      SPRING_PROFILES_ACTIVE: dev
      SPRING_KEYCLOAK_AUTH-SERVER-URL: http://host.docker.internal:8100
      SPRING_DATASOURCE_URL: jdbc:postgresql://famulex_db:5432/famulex

  famulex_db:
    image: postgres:14-alpine
    container_name: Famulex_DB
    volumes:
      - famulexDB:/var/lib/postgresql/data
    networks:
      - famulex
    environment:
      POSTGRES_USER: famulex
      POSTGRES_PASSWORD: famulex
      POSTGRES_DB: famulex


networks:
  famulex:
    name: famulex
    driver: bridge

volumes:
  famulexData:
    name: famulexData
  famulexDB:
    name: famulexDB
